const countries = [
  { title: 'Afghanistan', value: 'AF', code: 'AF' },
  { title: 'Albania', value: 'AL', code: 'AL' },
  { title: 'Algeria', value: 'DZ', code: 'DZ' },
  { title: 'Andorra', value: 'AD', code: 'AD' },
  { title: 'Angola', value: 'AO', code: 'AO' },
  { title: 'Antigua and Barbuda', value: 'AG', code: 'AG' },
  { title: 'Argentina', value: 'AR', code: 'AR' },
  { title: 'Armenia', value: 'AM', code: 'AM' },
  { title: 'Australia', value: 'AU', code: 'AU' },
  { title: 'Austria', value: 'AT', code: 'AT' },
  { title: 'Azerbaijan', value: 'AZ', code: 'AZ' },
  { title: 'Bahamas', value: 'BS', code: 'BS' },
  { title: 'Bahrain', value: 'BH', code: 'BH' },
  { title: 'Bangladesh', value: 'BD', code: 'BD' },
  { title: 'Barbados', value: 'BB', code: 'BB' },
  { title: 'Belarus', value: 'BY', code: 'BY' },
  { title: 'Belgium', value: 'BE', code: 'BE' },
  { title: 'Belize', value: 'BZ', code: 'BZ' },
  { title: 'Benin', value: 'BJ', code: 'BJ' },
  { title: 'Bhutan', value: 'BT', code: 'BT' },
  { title: 'Bolivia', value: 'BO', code: 'BO' },
  { title: 'Bosnia and Herzegovina', value: 'BA', code: 'BA' },
  { title: 'Botswana', value: 'BW', code: 'BW' },
  { title: 'Brazil', value: 'BR', code: 'BR' },
  { title: 'Brunei', value: 'BN', code: 'BN' },
  { title: 'Bulgaria', value: 'BG', code: 'BG' },
  { title: 'Burkina Faso', value: 'BF', code: 'BF' },
  { title: 'Burundi', value: 'BI', code: 'BI' },
  { title: 'Cabo Verde', value: 'CV', code: 'CV' },
  { title: 'Cambodia', value: 'KH', code: 'KH' },
  { title: 'Cameroon', value: 'CM', code: 'CM' },
  { title: 'Canada', value: 'CA', code: 'CA' },
  { title: 'Central African Republic', value: 'CF', code: 'CF' },
  { title: 'Chad', value: 'TD', code: 'TD' },
  { title: 'Chile', value: 'CL', code: 'CL' },
  { title: 'China', value: 'CN', code: 'CN' },
  { title: 'Colombia', value: 'CO', code: 'CO' },
  { title: 'Comoros', value: 'KM', code: 'KM' },
  { title: 'Congo (Congo-Brazzaville)', value: 'CG', code: 'CG' },
  { title: 'Congo (Congo-Kinshasa)', value: 'CD', code: 'CD' },
  { title: 'Costa Rica', value: 'CR', code: 'CR' },
  { title: 'Croatia', value: 'HR', code: 'HR' },
  { title: 'Cuba', value: 'CU', code: 'CU' },
  { title: 'Cyprus', value: 'CY', code: 'CY' },
  { title: 'Czech Republic', value: 'CZ', code: 'CZ' },
  { title: 'Denmark', value: 'DK', code: 'DK' },
  { title: 'Djibouti', value: 'DJ', code: 'DJ' },
  { title: 'Dominica', value: 'DM', code: 'DM' },
  { title: 'Dominican Republic', value: 'DO', code: 'DO' },
  { title: 'Ecuador', value: 'EC', code: 'EC' },
  { title: 'Egypt', value: 'EG', code: 'EG' },
  { title: 'El Salvador', value: 'SV', code: 'SV' },
  { title: 'Equatorial Guinea', value: 'GQ', code: 'GQ' },
  { title: 'Eritrea', value: 'ER', code: 'ER' },
  { title: 'Estonia', value: 'EE', code: 'EE' },
  { title: 'Eswatini', value: 'SZ', code: 'SZ' },
  { title: 'Ethiopia', value: 'ET', code: 'ET' },
  { title: 'Fiji', value: 'FJ', code: 'FJ' },
  { title: 'Finland', value: 'FI', code: 'FI' },
  { title: 'France', value: 'FR', code: 'FR' },
  { title: 'Gabon', value: 'GA', code: 'GA' },
  { title: 'Gambia', value: 'GM', code: 'GM' },
  { title: 'Georgia', value: 'GE', code: 'GE' },
  { title: 'Germany', value: 'DE', code: 'DE' },
  { title: 'Ghana', value: 'GH', code: 'GH' },
  { title: 'Greece', value: 'GR', code: 'GR' },
  { title: 'Grenada', value: 'GD', code: 'GD' },
  { title: 'Guatemala', value: 'GT', code: 'GT' },
  { title: 'Guinea', value: 'GN', code: 'GN' },
  { title: 'Guinea-Bissau', value: 'GW', code: 'GW' },
  { title: 'Guyana', value: 'GY', code: 'GY' },
  { title: 'Haiti', value: 'HT', code: 'HT' },
  { title: 'Honduras', value: 'HN', code: 'HN' },
  { title: 'Hungary', value: 'HU', code: 'HU' },
  { title: 'Iceland', value: 'IS', code: 'IS' },
  { title: 'India', value: 'IN', code: 'IN' },
  { title: 'Indonesia', value: 'ID', code: 'ID' },
  { title: 'Iran', value: 'IR', code: 'IR' },
  { title: 'Iraq', value: 'IQ', code: 'IQ' },
  { title: 'Ireland', value: 'IE', code: 'IE' },
  { title: 'Israel', value: 'IL', code: 'IL' },
  { title: 'Italy', value: 'IT', code: 'IT' },
  { title: 'Jamaica', value: 'JM', code: 'JM' },
  { title: 'Japan', value: 'JP', code: 'JP' },
  { title: 'Jordan', value: 'JO', code: 'JO' },
  { title: 'Kazakhstan', value: 'KZ', code: 'KZ' },
  { title: 'Kenya', value: 'KE', code: 'KE' },
  { title: 'Kiribati', value: 'KI', code: 'KI' },
  { title: 'Korea (North)', value: 'KP', code: 'KP' },
  { title: 'Korea (South)', value: 'KR', code: 'KR' },
  { title: 'Kuwait', value: 'KW', code: 'KW' },
  { title: 'Kyrgyzstan', value: 'KG', code: 'KG' },
  { title: 'Laos', value: 'LA', code: 'LA' },
  { title: 'Latvia', value: 'LV', code: 'LV' },
  { title: 'Lebanon', value: 'LB', code: 'LB' },
  { title: 'Lesotho', value: 'LS', code: 'LS' },
  { title: 'Liberia', value: 'LR', code: 'LR' },
  { title: 'Libya', value: 'LY', code: 'LY' },
  { title: 'Liechtenstein', value: 'LI', code: 'LI' },
  { title: 'Lithuania', value: 'LT', code: 'LT' },
  { title: 'Luxembourg', value: 'LU', code: 'LU' },
  { title: 'Madagascar', value: 'MG', code: 'MG' },
  { title: 'Malawi', value: 'MW', code: 'MW' },
  { title: 'Malaysia', value: 'MY', code: 'MY' },
  { title: 'Maldives', value: 'MV', code: 'MV' },
  { title: 'Mali', value: 'ML', code: 'ML' },
  { title: 'Malta', value: 'MT', code: 'MT' },
  { title: 'Marshall Islands', value: 'MH', code: 'MH' },
  { title: 'Mauritania', value: 'MR', code: 'MR' },
  { title: 'Mauritius', value: 'MU', code: 'MU' },
  { title: 'Mexico', value: 'MX', code: 'MX' },
  { title: 'Micronesia', value: 'FM', code: 'FM' },
  { title: 'Moldova', value: 'MD', code: 'MD' },
  { title: 'Monaco', value: 'MC', code: 'MC' },
  { title: 'Mongolia', value: 'MN', code: 'MN' },
  { title: 'Montenegro', value: 'ME', code: 'ME' },
  { title: 'Morocco', value: 'MA', code: 'MA' },
  { title: 'Mozambique', value: 'MZ', code: 'MZ' },
  { title: 'Myanmar', value: 'MM', code: 'MM' },
  { title: 'Namibia', value: 'NA', code: 'NA' },
  { title: 'Nauru', value: 'NR', code: 'NR' },
  { title: 'Nepal', value: 'NP', code: 'NP' },
  { title: 'Netherlands', value: 'NL', code: 'NL' },
  { title: 'New Zealand', value: 'NZ', code: 'NZ' },
  { title: 'Nicaragua', value: 'NI', code: 'NI' },
  { title: 'Niger', value: 'NE', code: 'NE' },
  { title: 'Nigeria', value: 'NG', code: 'NG' },
  { title: 'North Macedonia', value: 'MK', code: 'MK' },
  { title: 'Norway', value: 'NO', code: 'NO' },
  { title: 'Oman', value: 'OM', code: 'OM' },
  { title: 'Pakistan', value: 'PK', code: 'PK' },
  { title: 'Palau', value: 'PW', code: 'PW' },
  { title: 'Panama', value: 'PA', code: 'PA' },
  { title: 'Papua New Guinea', value: 'PG', code: 'PG' },
  { title: 'Paraguay', value: 'PY', code: 'PY' },
  { title: 'Peru', value: 'PE', code: 'PE' },
  { title: 'Philippines', value: 'PH', code: 'PH' },
  { title: 'Poland', value: 'PL', code: 'PL' },
  { title: 'Portugal', value: 'PT', code: 'PT' },
  { title: 'Qatar', value: 'QA', code: 'QA' },
  { title: 'Romania', value: 'RO', code: 'RO' },
  { title: 'Russia', value: 'RU', code: 'RU' },
  { title: 'Rwanda', value: 'RW', code: 'RW' },
  { title: 'Saint Kitts and Nevis', value: 'KN', code: 'KN' },
  { title: 'Saint Lucia', value: 'LC', code: 'LC' },
  { title: 'Saint Vincent and the Grenadines', value: 'VC', code: 'VC' },
  { title: 'Samoa', value: 'WS', code: 'WS' },
  { title: 'San Marino', value: 'SM', code: 'SM' },
  { title: 'Sao Tome and Principe', value: 'ST', code: 'ST' },
  { title: 'Saudi Arabia', value: 'SA', code: 'SA' },
  { title: 'Senegal', value: 'SN', code: 'SN' },
  { title: 'Serbia', value: 'RS', code: 'RS' },
  { title: 'Seychelles', value: 'SC', code: 'SC' },
  { title: 'Sierra Leone', value: 'SL', code: 'SL' },
  { title: 'Singapore', value: 'SG', code: 'SG' },
  { title: 'Slovakia', value: 'SK', code: 'SK' },
  { title: 'Slovenia', value: 'SI', code: 'SI' },
  { title: 'Solomon Islands', value: 'SB', code: 'SB' },
  { title: 'Somalia', value: 'SO', code: 'SO' },
  { title: 'South Africa', value: 'ZA', code: 'ZA' },
  { title: 'South Sudan', value: 'SS', code: 'SS' },
  { title: 'Spain', value: 'ES', code: 'ES' },
  { title: 'Sri Lanka', value: 'LK', code: 'LK' },
  { title: 'Sudan', value: 'SD', code: 'SD' },
  { title: 'Suriname', value: 'SR', code: 'SR' },
  { title: 'Sweden', value: 'SE', code: 'SE' },
  { title: 'Switzerland', value: 'CH', code: 'CH' },
  { title: 'Syria', value: 'SY', code: 'SY' },
  { title: 'Taiwan', value: 'TW', code: 'TW' },
  { title: 'Tajikistan', value: 'TJ', code: 'TJ' },
  { title: 'Tanzania', value: 'TZ', code: 'TZ' },
  { title: 'Thailand', value: 'TH', code: 'TH' },
  { title: 'Timor-Leste', value: 'TL', code: 'TL' },
  { title: 'Togo', value: 'TG', code: 'TG' },
  { title: 'Tonga', value: 'TO', code: 'TO' },
  { title: 'Trinidad and Tobago', value: 'TT', code: 'TT' },
  { title: 'Tunisia', value: 'TN', code: 'TN' },
  { title: 'Turkey', value: 'TR', code: 'TR' },
  { title: 'Turkmenistan', value: 'TM', code: 'TM' },
  { title: 'Tuvalu', value: 'TV', code: 'TV' },
  { title: 'Uganda', value: 'UG', code: 'UG' },
  { title: 'Ukraine', value: 'UA', code: 'UA' },
  { title: 'United Arab Emirates', value: 'AE', code: 'AE' },
  { title: 'United Kingdom', value: 'GB', code: 'GB' },
  { title: 'United States', value: 'US', code: 'US' },
  { title: 'Uruguay', value: 'UY', code: 'UY' },
  { title: 'Uzbekistan', value: 'UZ', code: 'UZ' },
  { title: 'Vanuatu', value: 'VU', code: 'VU' },
  { title: 'Vatican City', value: 'VA', code: 'VA' },
  { title: 'Venezuela', value: 'VE', code: 'VE' },
  { title: 'Vietnam', value: 'VN', code: 'VN' },
  { title: 'Yemen', value: 'YE', code: 'YE' },
  { title: 'Zambia', value: 'ZM', code: 'ZM' },
  { title: 'Zimbabwe', value: 'ZW', code: 'ZW' },
];

export default {
    name:'testimonials',
    title:'Testimonials',
    type: 'document',
    fields:[
        { 
            name:'name',
            title:'Name',
            type: 'string'
        },
        {
            name:'company',
            title:'Company',
            type:'string'
        },
        {
            name:'imgurl',
            title:'ImgUrl',
            type: 'image',
            options: {
              hotspot: true,
            },
        },  
        {
            name:'feedback',
            title:'Feedback',
            type:'string'
        },
        {
            name: 'country',
            title: 'Country',
            type: 'string',
            options: {
                list: countries.map(country => ({
                  title: country.title,
                  value: country.value,
                })),
              },
        }
    ]
}